name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      - name: Run tests with pytest
        run: pytest
  run_unit_test:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intstall apps
        uses: actions/setup-python@v1
        with: 
          python-version: 3.6
      - name: check folder
        run: |
          ls
          pwd
          cat /etc/os-release
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "::set-output name=test::hello"
          echo "::set-output name=test:step1"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

